### ISSUE TITLE
npm run build fails

### ISSUE THREAD

**Issue by MartinMajewski** [rodrigoelicer/electron-testing-app#1]
Running `npm run build` fails with the error message provided inside the attached debug.log.
However running `npm run electron` afterwards works. Seems that the build process has gone far enough to produce the needed files.

`npm run package` fails due to the dependency on the build process.

[npm-debug.log.zip](https://github.com/rodrigoelicer/electron-testing-app/files/658963/npm-debug.log.zip)

**Comment by rodrigoelicer** [comment]
Thanks for pointing it out! Since I used another repo as base, I deleted some files which are not totally needed for my purpose. Therefore I just needed to fix something on the build script from the package.json. Now there shouldn't be any problem (at least the npm run build)
